language: node_js
node_js:
  - "7"
before_install: 
  - cd tools
  - wget https://storage.googleapis.com/chromium-v8/node-linux-rel/node-linux-rel-41967-121bf38bc0a2973476ba378ddd3ff3b5f97ae494.zip -O nodejs.zip
  - unzip nodejs.zip
  - cd bin

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - wget
    - unzip

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: TEST_SUITE=test
    - os: linux
      node_js: "7"
      env: TEST_SUITE=lint
script: ./npm run $TEST_SUITE

